.TH CLIENT 1 "September 2026" "BSDSF23M009-OS-A01" "User Commands"
.SH NAME
client \- test driver program for libmyutils string and file functions
.SH SYNOPSIS
.B client
.SH DESCRIPTION
The
.B client
program is a driver application that demonstrates and tests the
functions provided by the libmyutils library, including string
manipulation functions (mystrlen, mystrcpy, mystrncpy, mystrcat)
and file utility functions (wordCount, mygrep).
.PP
Running the program will print the results of each function test
to standard output.
.SH AUTHOR
Written by Alisha (BSDSF23M009).
